---
version: "3.4"
services:
  nodejs:
    image: node
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    working_dir: /opt/node/nautobot
    user: node
    volumes:
      - ../nautobot_ui/:/opt/node/nautobot
      - ../:/source
    command: >
      bash -c "npm install && npm run start"
    depends_on:
      nautobot:
        condition: service_healthy
  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
      - nautobot
  nautobot:
    command: nautobot-server ourrunserver 0.0.0.0:8080 --insecure
