# Generated by Django 3.2.16 on 2022-11-20 19:44

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.roles


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0054_role_and_alter_status"),
        ("dcim", "0019_device_redundancy_group_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="device_role",
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="subdevice_role",
        ),
        migrations.AddField(
            model_name="device",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dcim_device_related",
                to="extras.role",
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dcim_devicetype_related",
                to="extras.role",
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dcim_rack_related",
                to="extras.role",
            ),
        ),
    ]
