# Generated by Django 3.2.16 on 2022-11-20 19:44

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.roles


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0054_role_and_alter_status"),
        ("ipam", "0008_prefix_vlan_vlangroup_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddress",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipam_ipaddress_related",
                to="extras.role",
            ),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipam_prefix_related",
                to="extras.role",
            ),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipam_vlan_related",
                to="extras.role",
            ),
        ),
    ]
