# Generated by Django 3.2.16 on 2022-11-20 19:44

from django.db import migrations
from django.db import models
import nautobot.extras.models.roles

# Before Altering the field; we need to get the name of the role it's connected to
# and use this role name to get its equivalent role from role model

temp_vm_id_and_role = {}


def get_virtualmachine_role_field_value(apps, schema):
    """Get all current model records id and role"""

    global temp_vm_id_and_role

    VirtualMachine = apps.get_model("virtualization", "VirtualMachine")
    data = VirtualMachine.objects.prefetch_related("role").filter(role__isnull=False).values("id", "role__name")
    temp_vm_id_and_role.update({item.id: item.role__name for item in data})


def set_virtualmachine_role_field_value(apps, schema):
    """Get all current model records id and role"""

    VirtualMachine = apps.get_model("virtualization", "VirtualMachine")
    Role = apps.get_model("extras", "Role")

    prev_vm_role_ids = [_id for _id, _ in temp_vm_id_and_role]

    VirtualMachine.objects.filter(id__in=prev_vm_role_ids).update(
        role=Role.objects.get(name=temp_vm_id_and_role[models.F("id")])
    )


# def reverse_set_virtualmachine_role_field_value(apps, schema):
#     """Reverse changes made by set_virtualmachine_role_field_value"""
#
#     VirtualMachine = apps.get_model("virtualization", "VirtualMachine")
#     Role = apps.get_model("extras", "Role")
#     DeviceRole = apps.get_model("dcim", "DeviceRole")
#
#



class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0055_collect_roles_from_related_apps_roles"),
        ("virtualization", "0009_cluster_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualmachine",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="virtualization_virtualmachine_related",
                to="extras.role",
            ),
        ),
    ]
